# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2ff4dbf7fc5e7e694e3a40c05f1bf759ebb6c399f7d17db5256bea1aded453abcf4956baea8faad4e8262fae2a5fa4e0ac68dba5abfa02f053b8c1442eaa828

test:
  secret_key_base: 2086c538d3ef95ca3b914f0caf87df0603eb8cfdcca218d11b02eddda51b82554a798a72f0b22573d2ab1376df8101378b0cbd7ea0f2bade08f11a9918fe35cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
